image: node:14.5.0

before_script:
  - apt-get update -qq && apt-get install

download_dependency:
  script: yarn
  only:
    changes:
      - ./

build:
  script: yarn build
  only:
    changes:
      - ./
